;==============================================================
; TILES FOR SPRITE 2 - (12 tiles total)
;==============================================================
; This data was generated by Beehive (see BigEvilCorporation's
; GitHub for source). BMP2TILE is another tool that can convert
; an image to this data format.
;
; Note that sprite tiles are layed out in COLUMN MAJOR, not
; row major like plane A/B cells.
;==============================================================

	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000002
	dc.l	0x00000002
	dc.l	0x00000112

	dc.l	0x00001222
	dc.l	0x00012772
	dc.l	0x00012772
	dc.l	0x00012222
	dc.l	0x00012222
	dc.l	0x00012777
	dc.l	0x00012777
	dc.l	0x00012777

	dc.l	0x00001222
	dc.l	0x00001112
	dc.l	0x00001112
	dc.l	0x00000001
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000

	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x02212222
	dc.l	0x1227777A
	dc.l	0x1227777A
	dc.l	0x2777AAAA

	dc.l	0x7777EEEA
	dc.l	0x777EEEEE
	dc.l	0x777EEEEE
	dc.l	0x777EEEEE
	dc.l	0x7777EEE7
	dc.l	0x27777777
	dc.l	0x27777777
	dc.l	0x22222777

	dc.l	0x22222222
	dc.l	0x21111111
	dc.l	0x21111111
	dc.l	0x11114448
	dc.l	0x00018EEE
	dc.l	0x00048EEE
	dc.l	0x00048EEE
	dc.l	0x00004448

	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x22221220
	dc.l	0xA7777221
	dc.l	0xA7777221
	dc.l	0xAAAA7772

	dc.l	0xAAAEE777
	dc.l	0xAAAEE777
	dc.l	0xAAAEE777
	dc.l	0xAAAA7777
	dc.l	0x77777777
	dc.l	0x7777777A
	dc.l	0x7777777A
	dc.l	0x7772222A

	dc.l	0x22222222
	dc.l	0x11111112
	dc.l	0x11111112
	dc.l	0x84441111
	dc.l	0x88841000
	dc.l	0x88844000
	dc.l	0x88844000
	dc.l	0x84440000

	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x20000000
	dc.l	0x20000000
	dc.l	0x21100000

	dc.l	0x22210000
	dc.l	0x72221000
	dc.l	0x72221000
	dc.l	0x72221000
	dc.l	0x72221000
	dc.l	0xA2221000
	dc.l	0xA2221000
	dc.l	0xA2221000

	dc.l	0x22210000
	dc.l	0x21110000
	dc.l	0x21110000
	dc.l	0x10000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000
	dc.l	0x00000000