;==============================================================
; TILES FOR SPRITE 1 - (4 tiles total)
;==============================================================
; This data was generated by Beehive (see BigEvilCorporation's
; GitHub for source). BMP2TILE is another tool that can convert
; an image to this data format.
;
; Note that sprite tiles are layed out in COLUMN MAJOR, not
; row major like plane A/B cells.
;==============================================================

	dc.l	0x00000888
	dc.l	0x00007788
	dc.l	0x00077788
	dc.l	0x07078888
	dc.l	0x07768868
	dc.l	0x87711111
	dc.l	0x08762218
	dc.l	0x88872228

	dc.l	0x88876677
	dc.l	0x00878877
	dc.l	0x88888888
	dc.l	0x08878888
	dc.l	0x00887788
	dc.l	0x00807788
	dc.l	0x00088788
	dc.l	0x00000808

	dc.l	0x80800000
	dc.l	0x77888000
	dc.l	0x88880800
	dc.l	0x88887880
	dc.l	0x86886780
	dc.l	0x11111888
	dc.l	0x71226780
	dc.l	0x82226800

	dc.l	0x78668878
	dc.l	0x88888888
	dc.l	0x88888888
	dc.l	0x88888080
	dc.l	0x87888880
	dc.l	0x88788800
	dc.l	0x00887000
	dc.l	0x80700000